blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/LindemannRock/craft-translation-manager/tree/main/docs
    about: Read the official documentation.
  - name: Craft Discord
    url: https://craftcms.com/discord
    about: Community discussion and support.
